### ISSUE TITLE
Instructions on how to configure

### ISSUE THREAD

**Issue by marcellodesales** [hyness/spring-cloud-config-server#1]
Hi there,
I know the config server requires the settings... Can you add the steps to configure the server? As you did not expose any volumes, I wonder how you are using this...

thanks

**Comment by hyness** [comment]
Hello Marcello:

Sorry, I didn't think anyone was using this repo but me.  I have added configuration and updated to the latest Spring Cloud Config Server.  Thanks for using this repo, I hope you found it useful.

**Comment by marcellodesales** [comment]
@hyness Hack yeah! Thanks a lot for providing this!!!! We can definitely expand this! :+1: I can contribute with a Docker-compose implementation... This definitely can help a lot of people!

I have a patch for Node.js support using JSON files and I'd like to experiment with your solution! https://github.com/spring-projects/spring-boot/issues/4027
