### ISSUE TITLE
Please update documentation for using mounted .ssh volumes

### ISSUE THREAD

**Issue by fennekit** [hyness/spring-cloud-config-server#105]
it took me a couple of days to find out that since the use of the Cloud Native buildpacks the .ssh directory is under /home/cnb/.ssh 
 `docker run --rm --name=test -it -p 8888:8888 -v $HOME/.ssh:/home/cnb/.ssh hyness/spring-cloud-config-server --spring.cloud.config.server.git.uri=git@github.com:user/private-github-repo.git --spring.cloud.config.server.git.default-label=main`

It might be useful to add this to the documentation or a wiki page. Posting this to save people tons of time.

_Originally posted by @fennekit in https://github.com/hyness/spring-cloud-config-server/issues/60#issuecomment-1376062484_

**Comment by hyness** [comment]
Updated README
