### ISSUE TITLE
Sccs with vault backend kubernetes auth method

### ISSUE THREAD

**Issue by Alesiks** [hyness/spring-cloud-config-server#15]
Current version of spring cloud config server(2.2.2.RELEASE) has a bug that header with Vault namespace isn't included into auth methods other than token. It  has been already fixed and will be included into next release.

But nevertheless there is a note in spring cloud config server specification: 
`If you omit the X-Config-Token header and use a server property to set the authentication, the Config Server application needs an additional dependency on Spring Vault to enable the additional authentication options. See the Spring Vault Reference Guide for how to add that dependency.`

So if we would like to use docker image with spring-cloud-config-server (vault backend and kubernetes authentication) the additional dependency for **spring-vault-core** should be added as a dependency ?

**Comment by hyness** [comment]
Hello @Alesiks.  I've wanted to conditionally add starters based on profiles for a while now, so I took some time to revisit this based on your request.  I tried to add `spring-cloud-starter-vault-config`, but I've not been able to make any progress.  From my research there is no way to exclude the `spring.factories` in the starters on the classpath.  I'm hesitant to blindly add `spring-vault-core`.  I can verify it doesn't break anything but it might not fix your issue.  So I will need some help from you to test this locally.  If it works for you without breaking anything, I'd gladly merge a pull request from you.  In the meantime if `2.2.2.RELEASE` has introduced a bug, perhaps you could downgrade to `2.2.1.RELEASE`?

**Comment by Alesiks** [comment]
Hi @hyness, 
Unfortunately we can't use `2.2.1.RELEASE` because of the bug which I have described above, it also presented in`2.2.1.RELEASE`. So we have to wait till the next release. 

Let wait for the new release. And in case if it will be needed to add additional maven dependency, I will try to prepare a pull request.

**Comment by hyness** [comment]
I’ve just updated the image to 2.2.3.RELEASE.  I’ve also included vault-core, as requested.  Please give it a try, and file a bug if you find any issues

**Comment by Alesiks** [comment]
Thanks it works!
