### ISSUE TITLE
Environment variable BANNER_LOCATION does not work.

### ISSUE THREAD

**Issue by norman-abramovitz** [hyness/spring-cloud-config-server#17]
The environment variable needs to be SPRING_BANNER_LOCATION instead of BANNER_LOCATION.

**Comment by hyness** [comment]
I'm not sure I understand this issue.  The banner location property comes from Spring Boot, not this docker image of Spring's Cloud Config Server which is built on top of Spring Boot.  You are free to configure this image with whatever properties or environment variables you wish.

**Comment by nabramovitz** [comment]
All I am saying in your docker-compose.yml file you use BANNER_LOCATION in the environment section and the real variable name is SPRING_BANNER_LOCATION.

**Comment by hyness** [comment]
At the time that compose file was written, it was the name of the property. I will remove the property from the example compose file.

**Comment by hyness** [comment]
Thanks for filing this issue.  It's lead me to clean up the example compose.  Hopefully it's intention will be clearer

**Comment by hyness** [comment]
The docker-compose has been removed and replaced with an examples directory with new docker-compose examples for backends, Al without the banner location
