### ISSUE TITLE
Implementation-Title and Implementation-Version are not populated

### ISSUE THREAD

**Issue by nabramovitz** [hyness/spring-cloud-config-server#19]
Using placeholders in a customized banner.txt file does not work anymore in the 2.2.3 release.  I use ${application.version}.  It did work in the 2.2.2 release.   The other static banner changes do display, so I know the path is correct.

https://docs.spring.io/spring-boot/docs/2.1.11.BUILD-SNAPSHOT/reference/html/boot-features-spring-application.html#boot-features-banner

**Comment by hyness** [comment]
This appears to be a bug in Spring Boot 2.3.0.RELEASE.  The `application.version` and `application.title` variables aren't being read from `META-INF/MANIFEST.MF`.  However other variables are working, such as `spring-boot.version`.  I think you'll need to file an issue with Spring Boot.  I don't see [any open issues](https://github.com/spring-projects/spring-boot/issues) regarding this bug

**Comment by norman-abramovitz** [comment]
Hi,

Here is the feedback I got.

https://github.com/spring-projects/spring-boot/issues/21647#issuecomment-637771111

**Comment by hyness** [comment]
I have to agree with the Spring Boot developers.  I've added the manifest entries to the build as they described.  I'm seeing the banner populated.  I pushed [a branch that demonstrates it working](https://github.com/hyness/spring-cloud-config-server/tree/wip-banner-works). 

- Checkout the branch above
- Run `gradle build`
- Run `java -jar build/libs/spring-cloud-config-server.jar`

**Comment by hyness** [comment]
Forgive my misunderstanding of this bug report.  The issue is fixed on the latest tag.  Sorry for having you file an invalid bug with Spring Boot

**Comment by norman-abramovitz** [comment]
No problem.    The good thing is, I have built up trust with you! 😄

**Comment by hyness** [comment]
Thank you so much @norman-abramovitz for all of these bug reports you’ve filed. Please don’t hesitate to file any additional issues you encounter.
