### ISSUE TITLE
register the config server on eureka

### ISSUE THREAD

**Issue by jangalinski** [hyness/spring-cloud-config-server#2]
I am replacing a custom spring-boot config server with this centralized image. Works fine, good work. But so far, my config server was also a discovery client and  registered itself on localhost:8761 ... is it possible to do so with this image as well? Or might this be supported?

**Comment by hyness** [comment]
Unfortunately, there isn't an easy way to add something like this.  If you look at the docker image, I build an executable jar and run that.  There's no easy way to dynamically add more jars to that jar.  More fundamentally, it kind of goes against the container way of doing things.  I think a better solution for you is use the [springcloud provided eureka image](https://hub.docker.com/r/springcloud/eureka/), bind that to port 8761 and link the image to this one.  In your other issue, I saw you are using compose.  It should be simple to add that image to the compose file.
