### ISSUE TITLE
application.yml does not seem to work in the 2.2.3 release.

### ISSUE THREAD

**Issue by nabramovitz** [hyness/spring-cloud-config-server#20]
It seems I can only get the environment variables to work for a GIT configuration.  It keeps claiming my application.yml file is invalid.   The same file use to work in the 2.2.2 release.

**Comment by hyness** [comment]
This issue has been fixed on the latest tag.  Re-pull the image and it should fix your issue.  I'll need to re-push the affected tags (2.2.3.RELEASE,2.1.8.RELEASE,2.1.9.RELEASE)

**Comment by norman-abramovitz** [comment]
Confirmed that the latest tag works with my existing application.yml file.
