### ISSUE TITLE
volume mount not working anymore

### ISSUE THREAD

**Issue by bessalahAmar** [hyness/spring-cloud-config-server#22]
simple run with a volume not working since 2 days ago. i can't get the files mounted.

`docker run -it -p 8888:8888  -v mypath:/config -e SPRING_PROFILES_ACTIVE=native hyness/spring-cloud-config-server`

`curl http://localhost:8888/service-dev.properties` will return empty
`cat /config/service-dev.properties` inside container will show the content of file correctly.

**Comment by hyness** [comment]
Fixed.  Thanks for the bug report and your interest in this image.

**Comment by bessalahAmar** [comment]
thank you 👍
