### ISSUE TITLE
https supports

### ISSUE THREAD

**Issue by RameshMuthuraj** [hyness/spring-cloud-config-server#6]
We have configured AWS ECS without ELB & mentioned spring uri as bitbucket ssh url

when i invoke the properties using https i'm getting error like below 

ttps://localhost:8888/api/test
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

could you please help me

**Comment by hyness** [comment]
This image doesn't support https.  If you need to add it, you can use a reverse proxy like nginx.  Why do you want to use https?  If it's not going to be accessed outside of docker, you don't need to to bind it to a host port.  Other containers can access it directly through docker.
