### ISSUE TITLE
Does this image support gitlab instead of a local repository?  

### ISSUE THREAD

**Issue by jeven2016** [hyness/spring-cloud-config-server#7]
Hi team,
   does this image support gitlab instead of a local repository? can I set http proxy or https proxy for git?

Thanks,
Jeven

**Comment by hyness** [comment]
Hello Jeven:

This image supports using both gitlab urls or local repositories checked out from gitlab.  In fact, it supports any git url.  It's not a feature of this image, it's a feature Spring Cloud Config.  I encourage you to read the excellent documentation provided by Spring Cloud Config, linked from both this github repo and the docker hub.

If you do happen to find an issue with this image not supporting a feature from the documentation, please file an issue like this one.  

Thank you for your interest in this image

**Comment by gfiguero937** [comment]
Hello, I just pulled your image and I’m trying to use it to connect to a gitlab project via https but it returns an error saying couldn’t clone the repo. I tried creating a conf server (no docker) and works but when I tried the Docker version it doesn’t.
Any clue what could be happening?

Thanks a lot
