### ISSUE TITLE
git with ssh

### ISSUE THREAD

**Issue by govindkailas** [hyness/spring-cloud-config-server#9]
I would like to see if there is a support available for git clone via ssh. 
Below is the command used to bring up the container
`docker run -it -p 8888:8888 \
      -e SPRING_CLOUD_CONFIG_SERVER_GIT_URI=sssh://git@gitlab.mydomain.com/AppConfig.git \
      docker pull hyness/spring-cloud-config-server`

Hitting config server url gives me the below 
```
There was an unexpected error (type=Not Found, status=404).
Cannot clone or checkout repository: ssh://git@gitlab.mydomain.com/AppConfig.git
```

**Comment by hyness** [comment]
The url you are using for ssh checkout is incorrect.  You should use the following url...

`git@gitlab.mydomain.com/AppConfig.git`

Please refer to the linked Spring Cloud Config Server documentation for further details

**Comment by govindkailas** [comment]
thanks @hyness I tried your suggestion. `git@gitlab.mydomain.com/AppConfig.git`  it doesnt work. 

I am referring this [spring doc](https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.0.0.RELEASE/single/spring-cloud-config.html#_git_ssh_configuration_using_properties)
Doc says `git@gitlab.mydomain.com:AppConfig.git` , tried this as well by adding the `:` instead of `/` sadly this too doesnt work.

**Comment by hyness** [comment]
What is the url you use to check it out from the command line?  That's what
you will use with this image.  I've used repositories hosted at gitlab and
github using ssh without issue, as I'm sure most others using this image.
