### ISSUE TITLE
Update on AWS Credentials Provider SDK

### ISSUE THREAD

**Issue by mourape** [hyness/spring-cloud-config-server#92]
Hello, we had some issues on AWS authentication, trying to **clone the repository using an IAM role**.
Actually the spring cloud config server provide the following ways to authenticate to AWS (the authentication will be taken by the following order):

1- Java System Properties - aws.accessKeyId and aws.secretAccessKey
2- Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
3 - Web Identity Token credentials from system properties or environment variables
4 - Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
5 - Credentials delivered through the Amazon EC2 container service if AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" environment 6 6 - variable is set and security manager has permission to access the variable,
7 - Instance profile credentials delivered through the Amazon EC2 metadata service

(You can find this information in the following link: [AWS SDK for Java](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) )

These ways of authentication are not available on the current image.
**We would need that because we cannot read the credentials assumed by the pod, only passing it manually via ENV VAR and we need the new version of AWS SDK with support to IAM role anywhere. Based on that we would like to ask an update on AWS SDK to a version above 2.10.**

Thanks in advance!

**Comment by hyness** [comment]
Hello @mourape ,

Thank you for your interest and support of this image.  I did look into upgrading to the AWS v2 libraries.  Spring Cloud Config has upgraded these libraries, but it will not be available until version 4.0.0.  [See the following upstream pull request](https://github.com/spring-cloud/spring-cloud-config/pull/2111) for further information.  Support will come as soon as it's available upstream.  I'll leave this issue open in the meantime

Thanks!
